default["teamcity-server"]["version"] = "7.1.5"
default["teamcity-server"]["postgresql"]["version"] = "9.2"
default["teamcity-server"]["postgresql"]["driver_version"] = "9.2-1002"
default["teamcity-server"]["postgresql"]["locale"] = "en_AU.UTF8"
default["teamcity-server"]["git"]["version"] = "1.8.3"
